### ISSUE TITLE
callbackURL is not in the latest NPM release

### ISSUE THREAD

**Issue by chrisli30** [liangyali/passport-wechat#14]
I need do dynamic Callback URL binding in Passport.Authenticate layer in my web app. The release version 2.0.2 in npm doesn't have your recent changes where callbackURL, state and scope could be overwritten. Could you consider releasing a new version with that feature? 

Thanks!

**Comment by liangyali** [comment]
v2.0.3 pushlished thanks

**Comment by chrisli30** [comment]
Thanks!
