### ISSUE TITLE
[问题]多进程运行，getToken和saveToken是必须设置的吗

### ISSUE THREAD

**Issue by tiaod** [liangyali/passport-wechat#20]
getToken: {getToken},
saveToken: {saveToken}

**Comment by tiaod** [comment]
研究分析了下，好像不设置也不影响多进程情况下passport-wechat的使用，不知道我理解是否正确。

**Comment by liangyali** [comment]
The `getToken` and `saveToken` can be provided to initialize Wechat OAuth instance. 只是用登陆的话可以不传也可以正常使用
