### ISSUE TITLE
可以根据url支持多appid吗？

### ISSUE THREAD

**Issue by julor** [liangyali/passport-wechat#5]
像这样支持：https://github.com/lutaoact/passport-weixin-plus多个appid吗？上一个作者应该停止维护了，有明显的bug。
求作者支持

**Comment by liangyali** [comment]
非常感谢您的反馈，我最近工作比较忙，我稍后会考虑进行支持

**Comment by julor** [comment]
感谢

**Comment by ilaipi** [comment]
这个feature现在支持了吗？
