### ISSUE TITLE
在回调的时候总是error

### ISSUE THREAD

**Issue by captain100** [liangyali/passport-wechat#9]
我能够得到accessToken refreshToken 和 profile的值 使用 done（null , profile）总是 400 为什么呢
[Tue, 22 Dec 2015 06:34:53 GMT] "GET /api/user/auth/wechat" 302 2.512 ms 0
accessToken =  OezXcEiiBSKSxW0eoylIePearzUkTO6p3rVb1p-rOuLbThz-b4NJ_F9rmlt9OTh8VdcY6WOSsawWxgD5F24Yx_ktwzsEcAyfCkIh_GEnw5Cw8GfLW9hPOC-NQ3sMkkVYlgAxSSg5LT5PsvsEnStDSw
refreshToken =  OezXcEiiBSKSxW0eoylIePearzUkTO6p3rVb1p-rOuLbThz-b4NJ_F9rmlt9OTh8J4yZ2jOV_5NCO7iVscqOkxThtH7KUGPeduqnQMjDwS5ndJ7VmfD9B0Pv3wDSCSgqN-qZQSFlK8yDVUqEyEMQWQ
{ openid: 'on1lHxN-JI-eUE4F0Ha4p5x5p6ZE', unionid: undefined }

[Tue, 22 Dec 2015 06:37:08 GMT] "GET /api/user/auth/wechat/callback?code=011925dd48552cfcd02019b1df52528o&state=STATE" 400 170.527 ms 38

**Comment by liangyali** [comment]
能提供更多的信息吗？请使用最新版本，我这里一直在线上运行没有发现问题
